### ISSUE TITLE
More advanced translation scopes

### ISSUE THREAD

**Issue by pavelbonda** [excid3/noticed#130]
Hi!

Currently when I use translation method `t('.message')` in class `Admin::SomeNotification` it returns following translation:
```yml
notifications: 
  admin/some_notification:
    message: Some
```
This approach does not benefit from `yaml` nesting and leads to some duplication. It would be good to have an option to use following translation path for described case:
```yml
notifications:
  admin:
    some_notification:
      message: Some
```
