### ISSUE TITLE
Notification model attribute type is generating testing errors for other classes

### ISSUE THREAD

**Issue by dvodvo** [excid3/noticed#69]
Upon running a test for a different class `rails test test/controllers/roleusers_controller_test.rb`

The error:
```
RoleusersControllerTest#test_should_get_edit:
DRb::DRbRemoteError: PG::NotNullViolation: ERROR:  null value in column "type" violates not-null constraint
DETAIL:  Failing row contains (980190962, Recipient, 980190962, null, null, 2020-11-27 21:19:12, 2020-11-28 10:27:11.443691, 2020-11-28 10:27:11.443691)
```
Checking the application schema, there is only one instance of a column with the name `type` and it is with the column of the `notifications` table which thus had passed to postgresql upon its migration generation: `t.string "type", null: false` 

I've traced the mistake to the fixture:
```
one:
  recipient: one
  recipient_type: Recipient
  type: 
  params: 
  read_at: 2020-11-27 21:19:12
```

By populating` type` and `params` with dummy data `MyString` and `1`, the test passes.    
The gem read_me does not indicate what is expected for the type attributes, which might be helpful is the model were extended with other attributes, then subjected to testing.

**Comment by excid3** [comment]
`type` should be the notification class' name. If you had a CommentNotification, then the `type` should be set to `CommentNotification`.

**Comment by excid3** [comment]
@evanshabsove Just added an example fixture and a test to the repo. 👍  https://github.com/excid3/noticed/commit/9d406db33d51296cee2792c13c04421f077418e5

The mistake in your fixture is that the `_aj_symbol_keys` should be at the top level in `params`, not nested under `task`.

```yaml
one:
  recipient: one (User)
  type: "TaskAssignedNotification"
  params:
    task:
      _aj_globalid: gid://app/Task/<%= ActiveRecord::FixtureSet.identify(:two) %>
    _aj_symbol_keys:
    - task
  read_at:
 ```

The other addition is using `identify` to dynamically set the ID since it's dynamically generated.
